### ISSUE TITLE
isFocused immediately true in TabNavigator

### ISSUE THREAD

**Issue by MSchmidt** [pmachowski/react-navigation-is-focused-hoc#2]
Thanks for trying to figure this out. I've added this to the second tab in a ``TabNavigator`` and it mostly works. However, when the TabNavigator loads (on first tab) the prop (for second tab) is immediately ``true``. Then no ``componentWillReceiveProps`` is triggered when I switch to the tab. After that everything works as expected.

**Comment by cidylle** [comment]
I'm having the same issue, with `TabNavigator`, `isFocused` is true by default on every single component it is attached to. Only after switching tabs first then the value is correctly updated.

**Comment by ugiacoman** [comment]
Check out the PR @cidylle @MSchmidt

**Comment by MSchmidt** [comment]
@ugiacoman nice, put this in and it works great.

**Comment by peter-mach** [comment]
The fix is in the v.1.1.0
