### ISSUE TITLE
RouteName is not unique id for screen. Please use key

### ISSUE THREAD

**Issue by punksta** [pmachowski/react-navigation-is-focused-hoc#7]
If you have complex structure, one screen can be used in few navigators. Also one screen can be used many times in one StackNavigator by accepting different params. Example: photo gallery, folder explorer.

So please, use `route.key` instead

**Comment by lprhodes** [comment]
Seconded, unique id's would be really great

**Comment by patlux** [comment]
@punksta @lprhodes 

I added a pull request to fix this. #8

**Comment by peter-mach** [comment]
It's implemented in v1.1.0 thanks for feedback!
